export const SECTOR_OPTIONS = [
  { id: 'pharmaceuticals', label: 'Pharmaceuticals' },
  { id: 'apis', label: 'APIs & Fine Chemicals' },
  { id: 'formulations', label: 'Formulations & Generics' },
  { id: 'biotech', label: 'Biotechnology & Biologics' },
  { id: 'medical-devices', label: 'Medical Devices' },
  { id: 'diagnostics', label: 'Diagnostics & IVD' },
  { id: 'surgical-equipment', label: 'Surgical Equipment' },
  { id: 'hospital-solutions', label: 'Hospital Solutions' },
  { id: 'digital-health', label: 'Digital Health' },
  { id: 'health-tech', label: 'Health-Tech & AI' },
  { id: 'healthcare-services', label: 'Healthcare Services' },
  { id: 'contract-manufacturing', label: 'Contract Manufacturing (CDMO)' },
  { id: 'nutraceuticals', label: 'Nutraceuticals & Wellness' },
  { id: 'laboratory-equipment', label: 'Laboratory Equipment' },
  { id: 'medical-technology', label: 'Medical Technology' },
  { id: 'healthcare-infrastructure', label: 'Healthcare Infrastructure & Facilities' },
  { id: 'rehabilitation-elder-care', label: 'Rehabilitation & Elder Care' },
  { id: 'medical-tourism', label: 'Medical Tourism & Networks' },
  { id: 'allied-healthcare', label: 'Allied Healthcare Businesses' },
];
